---
title: "model"
author: "guy kiper"
date: "6/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message=FALSE}
library(tidymodels)
library(tidytext)
library(dplyr)
library(ggplot2)
library(tidyr)
library(rvest)
library(stringr)
library(lubridate)
library(readr)
library(gridExtra)
library(grid)
```
 #################part 1 ###########################
 
```{r}
#load csv of filtered wiki
df_wiki_filtered <- read.csv("df_wiki_numeric.csv")
df_wiki_filtered <- df_wiki_filtered[,2:ncol(df_wiki_filtered)]
civiqs_poll_data <- read.csv("civiqs_poll.csv")
#load the summarised stats
summmarised_stats <- read.csv("summarised_stats.csv") 
summmarised_stats <- summmarised_stats[,2:ncol(summmarised_stats)]
summmarised_stats$Date <-ymd(summmarised_stats$Date)
civiqs_poll_data$sum_rep_dem <- civiqs_poll_data$dem+civiqs_poll_data$rep

filtered_summ <- summmarised_stats[12:52,]
df_governors <- read.csv("us-governors.csv")

```
 
 
```{r}
#Summed concern level agains the active cases
plot_active_cases_dates <- ggplot(filtered_summ,mapping = aes(x=Date,y=Active))+
  labs(title='Active Case',y="Active Cases")+
  xlab(NULL)+geom_line()+
  scale_y_continuous(trans=log2_trans(), breaks = trans_breaks("log2", function(x) 2^x),labels = trans_format("log2", math_format(2^.x)))
plot_polls_dates <- ggplot(civiqs_poll_data,aes(x=Date,y=sum_rep_dem))+geom_line()+labs(title='Concern Level',y='Level',x='Date')
grid.arrange(plot_active_cases_dates,plot_polls_dates,top=textGrob("The Effect of Active Cases on the Concern of the Citizens",gp=gpar(fontsize=15,font=2)))

```
 
 
```{r}
#function to get the party of the state

get_party <- function(x){
  temp_vec <- grepl(x,df_governors$state_code)
  if (any(temp_vec)){
    row_num <- min(which(temp_vec==T))
    df_governors$party[row_num]
  }
  else{
    "None"
  }
} #given a state code, receive the party it's connected to

```
 
 
 
```{r}
rep_list <-list()
list_index=1
rep_list[list_index] <- "Date"
list_index <- list_index+1
for (i in 2:ncol(df_wiki_filtered)){
  state <- colnames(df_wiki_filtered)[i]
  if(get_party(state)=="republican"){
    rep_list[list_index] <- state
    list_index <- list_index+1
  }
} #get list of all the republican states

```
 
 
 
 
```{r}
rep_list <- unlist(rep_list)
republican_states <- df_wiki_filtered[rep_list] #dataframe with the republican states

longer_republican_states <- republican_states%>%pivot_longer(cols=-Date, names_to="State", values_to="Value")

ggplot(longer_republican_states, aes(x=Date,y= Value))+xlab(NULL)+
  geom_line(aes(color= "#DE0100"))+facet_wrap(.~State)+theme(legend.position="none")+
  labs(title="Covid-19 Infections In Republican States",subtitle = "Dates 21/01/2020 - 26/05/2021",y="Number Of Infections")

```
 
 
```{r}
#infections per mounth

by_month <- summmarised_stats
by_month$y_m <- floor_date(by_month$Date,"month")

by_mounth <- by_month%>%group_by(y_m)%>%summarize(value=sum(Confirmed_daily))%>%as.data.frame() 

ggplot(by_mounth, aes(x=y_m,y=value))+geom_bar(stat='identity',fill="blue")+
  scale_x_date(date_breaks="1 month",labels= date_format("%y/%m"))+scale_y_continuous(labels=comma)+
  labs(title="Infections per Month",subtitle = "January 2020 - May 2021",y="Total Monthly Infections")+
  xlab(NULL)+ theme(plot.title = element_text(size=22), plot.subtitle = element_text(size=12))

```
 
```{r}
#republican concern vs infections

rep_concern <- ggplot(civiqs_poll_data,aes(x=Date,y=rep))+geom_line(aes(color="#DE0100"))+
  labs(title = "Republican Concern Level",y="Concern Level")+
  xlab(NULL)+theme(legend.position="none")
  

```
 
```{r}
republican_total_infections <- longer_republican_states%>%group_by(Date)%>%
  summarize(value=sum(Value))%>%as.data.frame()
```
 
 
```{r}
rep_infections <- ggplot(republican_total_infections%>%filter(Date>="2020-02-25" & Date<="2020-04-05"),
                         aes(x=Date,y=value))+geom_line(aes(color="#DE0100"))+theme(legend.position="none")+
  labs(title="Total Infections in Republican States",y="Number Of Daily Infections")
grid.arrange(rep_concern,rep_infections,top=textGrob("The Effect of Daily Infections in Republican States", gp=gpar(fontsize=20,font=2)),
             bottom=textGrob("25/02/2020 - 05/04/2020", gp=gpar(fontsize=16)))

```
 

 
 ################part 2###########################
#### download data ,changing in the formats , adding information
```{r}

civiqs_poll_data <- read.csv("civiqs_poll.csv")
colnames(civiqs_poll_data)[1] <- "Date"
civiqs_poll_data$Date <-as.Date(civiqs_poll_data$Date,format="%m/%d/%y")
head(civiqs_poll_data)

```



```{r}
trump_tweet_data <- readRDS("trump.rds") %>%
  rownames_to_column(var = "speech_id")
colnames(trump_tweet_data)[2] <- "Date"
trump_tweet_data$Date<-substr(trump_tweet_data$Date,1,10)
trump_tweet_data$Date<- as.Date(trump_tweet_data$Date)
trump_tweet_data$length_text <-str_count(trump_tweet_data$text)
head(trump_tweet_data)
```


```{r}
speech_join_rep <- inner_join(trump_tweet_data,civiqs_poll_data ,by ="Date" )
speech_join_rep<-speech_join_rep %>% select(Date,speech_id,rep)
speech_join_rep$speech_id <- as.numeric(as.character(speech_join_rep$speech_id))
head(speech_join_rep)

```



```{r }


# separate into sentences
trump_tweet_data_sentences <- trump_tweet_data %>%
  unnest_tokens(sentence, text, token = "sentences")

# check the balance between retweet and nonretweet
ggplot(trump_tweet_data_sentences, aes(x = isRetweet,fill  = isRetweet)) +
  geom_bar()+
  labs(title = "the amount of tweet and retweet by trump",
       x = NULL ,y = NULL)

```


Explanation:

we can see from the gragh that there isnt a big diffrent between the amount retweet and tweet by trump




```{r }

trump_tweet_data_word <-trump_tweet_data %>%
  rowwise()%>%
  mutate(sum_words = text %>% str_count("\\w+")%>% sum()) %>%
  ungroup() %>%
  unnest_tweets(word,text)

```


```{r}
head(trump_tweet_data_word)
```


```{r}





ggplot(trump_tweet_data_word,aes(x=sum_words,fill = isRetweet))+
  geom_bar()+
  facet_grid(isRetweet~.,scales = "free")+
  labs(title = "the amount of word when trump tweet and retweet",
       x = NULL , y = NULL)


```

Explanation:

we can see that there is a diffrent between the amount of words
when trump tweets and retweets, when trump tweet the sum of the tweet
is larger the in a retweet .



```{r }
trump_top_500_ngrams <- trump_tweet_data %>% 
  unnest_tokens(n_grams, text, token = "ngrams", n = 3, n_min = 1) %>% 
  anti_join(stop_words, by = c("n_grams" = "word")) %>%    # drop rows with stop words
  group_by(n_grams) %>%    # group by bigram index
  summarise(n_grams = unique(n_grams), n = n(), .groups = "drop") %>% 
  arrange(desc(n)) %>% 
  rowid_to_column(var = "id") %>% 
  filter(id<=200) %>%
print(0)  
trump_top_500_ngrams<- trump_top_500_ngrams[-grep('rt',trump_top_500_ngrams$n_grams),]
trump_top_500_ngrams<- trump_top_500_ngrams[-grep('https',trump_top_500_ngrams$n_grams),]
trump_top_500_ngrams<- trump_top_500_ngrams[-grep('t.co',trump_top_500_ngrams$n_grams),]

```

```{r}
head(trump_top_500_ngrams)
```



```{r include=FALSE}


trump_tweets_tf_idf_wide <- trump_tweet_data %>% 
  unnest_tokens(n_grams, text, token = "ngrams", n = 3, n_min = 1, drop = FALSE) %>% 
  anti_join(stop_words, by = c("n_grams" = "word")) %>% 
  group_by(speech_id, n_grams) %>% 
  summarise(n = n()) %>% 
  bind_tf_idf(n_grams,document = speech_id, n = n) %>% 
  filter(n_grams %in% trump_top_500_ngrams$n_grams) %>% 
  pivot_wider(id_cols = speech_id,
              names_from = n_grams,
              values_from = tf_idf,
              values_fill = 0)
trump_tweets_tf_idf_wide$speech_id <- as.numeric(as.character(trump_tweets_tf_idf_wide$speech_id))

trump_tweets_tf_idf_wide<-
  cbind(trump_tweets_tf_idf_wide, total = rowSums(trump_tweets_tf_idf_wide)-trump_tweets_tf_idf_wide$speech_id)

```





```{r}


trump_tweet_sum_td_idf <- trump_tweets_tf_idf_wide %>% select(speech_id,total)
rep_tf_idf <- inner_join(trump_tweet_sum_td_idf ,speech_join_rep, by = "speech_id")
head(rep_tf_idf)

```


```{r}

trump_tweets_tf_idf_long <- trump_tweet_data %>% 
  unnest_tokens(n_grams, text, token = "ngrams", n = 3, n_min = 1, drop = FALSE) %>% 
  anti_join(stop_words, by = c("n_grams" = "word")) %>% 
  group_by(speech_id, n_grams) %>% 
  summarise(n = n()) %>% 
  bind_tf_idf(n_grams,document = speech_id, n = n) %>% 
  filter(n_grams %in% trump_top_500_ngrams$n_grams) 

head(trump_tweets_tf_idf_long)

```



```{r}
ggplot(rep_tf_idf, aes(x = total, y = rep,size = total)) +
  geom_point(aes (color = rep , alpha = 0.7)) +
  geom_smooth(method = "lm", formula = y ~ x)+
  labs(title = " the republican concern level vs sum of tf_idf tweet",
       x = "sum of tf_idf tweet",
       y = " republican concern level")+
  guides(alpha = FALSE ,smooth = FALSE)

```


```{r}
cor(rep_tf_idf$total,rep_tf_idf$rep)

```

```{r}

set.seed(1234)
cov_split <- initial_split(rep_tf_idf )
cov_train <- training(cov_split)
cov_test <- testing(cov_split)
```

```{r}

cov_mod <- linear_reg()%>%
  set_engine("lm") 
```

```{r}
cov_rec <- recipe(rep ~ total,data=cov_train) 

```

```{r}
cov_wflow <- workflow() %>%
  add_model(cov_mod) %>%
  add_recipe(cov_rec)

```

```{r}
set.seed(1234)
cov_folds <- vfold_cv(cov_train, v = 3)
write_rds(cov_folds, "cov_folds.rds", compress = "bz2")

civiqs_poll_data_folds <- read_rds("cov_folds.rds")

```

```{r}
cov_fit_rs <- cov_wflow %>%
  fit_resamples(
    cov_folds,
    control = control_resamples(save_pred = TRUE)
  )
```

```{r}


collect_metrics(cov_fit_rs)
collect_predictions(cov_fit_rs)

```

